[tool.poetry]
name = "test"
version = "0.1.0"
description = ""
authors = ["Lightricks <dgang@lightricks.com>"]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "0.115.12"
pydantic = "2.11.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"